/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.network.university.directorateOrganization;

import biz.EcoSystem;
import biz.account.Account;
import biz.enterprises.AdCompanyEnterprise;
import biz.enterprises.ECOEnterprise;
import biz.enterprises.Enterprise;
import biz.enterprises.NPOEnterprise;
import biz.org.Organization;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import ui.components.HasTitle;
import ui.components.ParentUI;
import ui.components.TablePopulatable;

/**
 *
 * @author royn
 */
public class CreateEnterprise extends javax.swing.JPanel implements HasTitle{
    private ParentUI parentUI;
    private Account account;
    private AdCompanyEnterprise adCompanyEnterprise;
    private ECOEnterprise ecoEnterprise;
    private NPOEnterprise nPOEnterprise;
    /**
     * Creates new form ManageColleges
     */

    CreateEnterprise(ParentUI parent, Account account) {
        this.parentUI = parent;
        this.account = account;
        populateCombobox();
    }
    
    private void tmpNewEnterprises(){
        this.adCompanyEnterprise = new AdCompanyEnterprise("Advertisement Company", account.getOrg().getEnterprise().getNetwork());
        this.ecoEnterprise = new ECOEnterprise("Extra Curricular Organization", account.getOrg().getEnterprise().getNetwork());
        this.nPOEnterprise = new NPOEnterprise("Non-profit Organization", account.getOrg().getEnterprise().getNetwork());
    }
    
    private void populateCombobox(){
        cbType.removeAllItems();
        cbType.addItem(adCompanyEnterprise);
        cbType.addItem(ecoEnterprise);
        cbType.addItem(nPOEnterprise);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbType = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setText("Add Company");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Company name:");

        cbType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Company type:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(393, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(118, 118, 118)
                .addComponent(jButton1)
                .addGap(203, 203, 203))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(txtName.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please input a valid name");
            return;
        }
        
        tmpNewEnterprises();
        
        Enterprise e = (Enterprise) cbType.getSelectedItem();
        e.setName(txtName.getText());
        
        try{
            if(e instanceof AdCompanyEnterprise){
            account.getOrg().getEnterprise().getNetwork().getAdCompanyCatalog().getEnterprises().add((AdCompanyEnterprise) e);
        }else if(e instanceof ECOEnterprise){
            account.getOrg().getEnterprise().getNetwork().getEcoCatalog().getEnterprises().add((ECOEnterprise) e);
        }else if(e instanceof ECOEnterprise){
            account.getOrg().getEnterprise().getNetwork().getNpoCatalog().getEnterprises().add((NPOEnterprise) e);
        }
        }catch(Exception exception){
            JOptionPane.showMessageDialog(this, "something going wrong");
        }
        
        
        JOptionPane.showMessageDialog(this, "You are all set!");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbType;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTitle() {
        return "Create College Page";
    }
}
