/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.network.university.directorateOrganization;

import biz.account.Account;
import biz.nw.Network;
import ui.components.HasTitle;

import javax.swing.*;

/**
 *
 * @author hezj
 */
public class ManageCoinK0 extends javax.swing.JPanel implements HasTitle {
    private Network network;
    
    /**
     * Creates new form ManageCoinK0
     */
    public ManageCoinK0(Account account) {
        network = account.getOrg().getEnterprise().getNetwork();
        initComponents();
        txK0.setText(String.format("%.2f", network.getK0()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txK0 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn = new javax.swing.JButton();

        jLabel1.setText(" Base Coin Price:");

        btn.setText("Save");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(368, 368, 368)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(txK0)
                    .addComponent(btn, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
                .addContainerGap(374, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txK0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn)
                .addContainerGap(509, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        String k0Str = txK0.getText();
        double k0;
        try {
            k0 = Double.parseDouble(k0Str);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid value.", "Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (k0 < 0.01) {
            JOptionPane.showMessageDialog(this, "Invalid value. Base Price must be no less than 0.01", "Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }
        network.setK0(k0);
        JOptionPane.showMessageDialog(this, "Saved!");
    }//GEN-LAST:event_btnActionPerformed

    @Override
    public String getTitle() {
        return String.format("Manage Base Coin Price of %s", network);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txK0;
    // End of variables declaration//GEN-END:variables
}
