/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.network.university.accountingOrganization;

import biz.account.Account;
import biz.enterprises.AdCompanyEnterprise;
import biz.fnc.AdViewsOrder;
import java.util.stream.Stream;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import ui.components.HasTitle;
import ui.components.TablePopulatable;

/**
 *
 * @author 79813
 */
public class ManageAdOrderRequest extends javax.swing.JPanel implements TablePopulatable<AdViewsOrder>,HasTitle{
    private Account account;
    /**
     * Creates new form ManageAdOrderRequest
     */
    public ManageAdOrderRequest(Account account) {
        initComponents();
        this.account = account;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequest = new javax.swing.JTable();
        btnApprove = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();

        tblRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Create Time", "Company Name", "Quantity", "Information", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblRequest);

        btnApprove.setText("Approve");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(btnApprove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReject)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        AdViewsOrder order = getSelected();
        if(order == null){
            return;
        }
        try{

            order.approve();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Cannot approve because of some system reasons");
            populateTable();
        }
        JOptionPane.showMessageDialog(this, "Approved");
        populateTable();
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        AdViewsOrder order = getSelected();
        if(order == null){
            return;
        }
        try{
            order.reject();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Cannot reject because of some system reasons");
            populateTable();
        }
        JOptionPane.showMessageDialog(this, "Rejected");
        populateTable();
    }//GEN-LAST:event_btnRejectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnReject;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRequest;
    // End of variables declaration//GEN-END:variables

    @Override
    public JTable getTable() {
        return tblRequest;
    }

    @Override
    public Object[] populateRow(AdViewsOrder element) {
        return new Object[]{
            element,
            element.getCompany().getName(),
            element.getQuantity(),
            element.getInformation(),
            element.getStatus()
        };
    }

    @Override
    public void populateTable() {
        for(AdCompanyEnterprise companyEnterprise : account.getOrg().getEnterprise().getNetwork().getAdCompanyCatalog().getEnterprises()){
            Stream<AdViewsOrder> stream = companyEnterprise.getAdViewsOrderCatalog().getAdViewsOrders()
                .stream().filter(e -> e.getStatus().equals(AdViewsOrder.Status.Submitted));
            populateTable(stream);
        }
    }

    @Override
    public String getTitle() {
        return "Manage Advertisement Order Request";
    }
}
