/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.network.university.saleOrganization.SalesManager;

import ui.network.university.saleOrganization.SalesPerson.*;
import biz.account.Account;
import biz.contract.Contract;
import biz.contract.ContractCatalog;
import biz.nw.Network;
import biz.role.salesRole.SalesManagerRole;
import biz.role.supervisorRole.UniversitySupervisorRole;
import java.util.stream.Stream;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import ui.components.HasTitle;
import ui.components.ParentUI;
import ui.components.TablePopulatable;

/**
 *
 * @author royn
 */
public class CensorContracts extends javax.swing.JPanel implements HasTitle, TablePopulatable<Contract> {
    private ParentUI parent;
    private Network network;
    private Account account;

    /**
     * Creates new form ManageContracts
     */
    public CensorContracts(ParentUI parent, Account account) {
        initComponents();
        this.account = account;
        this.network = account.getOrg().getEnterprise().getNetwork();
        this.parent = parent;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblContract = new javax.swing.JTable();
        btnDeny = new javax.swing.JButton();
        btnApprove = new javax.swing.JButton();

        tblContract.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Company Name", "Basic Price", "Signed By", "Sign at", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblContract);

        btnDeny.setText("Deny");
        btnDeny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDenyActionPerformed(evt);
            }
        });

        btnApprove.setText("Approve");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 886, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnApprove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeny, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnApprove)
                        .addGap(70, 70, 70)
                        .addComponent(btnDeny))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDenyActionPerformed
        // TODO add your handling code here:
        Contract selected = getSelected();
        if (selected == null) {
            return;
        }
        
        selected.setContractStatus(Contract.ContractStatus.Banned);
        JOptionPane.showMessageDialog(this, "Contract Banned!");
        populateTable();
    }//GEN-LAST:event_btnDenyActionPerformed

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:
        Contract selected = getSelected();
        if (selected == null) {
            return;
        }
        
        if (account.getRole() instanceof SalesManagerRole){
            selected.setContractStatus(Contract.ContractStatus.SMApproved);
        }else if(account.getRole() instanceof UniversitySupervisorRole){
            selected.setContractStatus(Contract.ContractStatus.NSApproved);
            selected.getAdCompanyEnterprise().setIsActive(true);
        }
        
        JOptionPane.showMessageDialog(this, "Contract Approved!");
        populateTable();
    }//GEN-LAST:event_btnApproveActionPerformed

    @Override
    public String getTitle() {
        return String.format("Manage Contracts under %s", account.getPerson());
    }

    @Override
    public JTable getTable() {
        return tblContract;
    }

    @Override
    public Object[] populateRow(Contract element) {
        return new Object[]{
            element,
            element.getAdCompanyEnterprise().getK0(),
            element.getAccount(),
            element.getSignedAt().getTime(),
            element.getContractStatus()
        };
    }

    @Override
    public void populateTable() {
        ContractCatalog ctlg = account.getOrg().getEnterprise().getNetwork().getContractCatalog();
        Stream<Contract> c = ctlg.getContractArrayList().stream(); 
        if (account.getRole() instanceof SalesManagerRole){
            c = c.filter(v -> v.getAccount().getOrg().equals(account.getOrg()) && v.getContractStatus().equals(Contract.ContractStatus.Created));
        }else if(account.getRole() instanceof UniversitySupervisorRole){
            c = c.filter(v -> v.getAccount().getOrg().getEnterprise().getNetwork().equals(account.getOrg().getEnterprise().getNetwork()) 
                    && v.getContractStatus().equals(Contract.ContractStatus.SMApproved));
        }
        populateTable(c);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnDeny;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblContract;
    // End of variables declaration//GEN-END:variables
}
