/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import hlp.fkr.EcoSystemHelper;
import ui.components.TopBar;
import ui.components.ParentUI;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import ui.components.BiubiuBrowser;
import ui.network.university.college.viewer.anonymous.AnonymousHomePage;


/**
 *
 * @author hezj
 */
public class MainJFrame extends javax.swing.JFrame implements ParentUI {
    private TopBar topBar;
    
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        BiubiuBrowser.getInstance().browser.loadURL("about:blank");
        topBar = TopBar.getInstance(this);
        initComponents();
        this.add(topBar, BorderLayout.PAGE_START);
        this.pushComponent(new AnonymousHomePage(this));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 750));
        setMinimumSize(new java.awt.Dimension(1000, 750));
        setSize(new java.awt.Dimension(1000, 700));

        container.setLayout(new java.awt.CardLayout());
        getContentPane().add(container, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        EcoSystemHelper.configure();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    // End of variables declaration//GEN-END:variables

    @Override
    public JPanel getContainerJPanel() {
        return container;
    }

    @Override
    public void componentPoped() {
        int count = this.container.getComponentCount();
        if (count <= 1) {
            this.topBar.loggedOut();
        }
        
        if (this.container.getComponentCount() <= 0) {
            this.pushComponent(new AnonymousHomePage(this));
        }
    }

    @Override
    public void allComponentsPoped() {
        this.pushComponent(new AnonymousHomePage(this));
    }

    }
