/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.sysadmin;

import biz.EcoSystem;
import biz.account.Account;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import ui.components.HasTitle;
import ui.components.ParentUI;
import ui.components.TablePopulatable;

/**
 *
 * @author 79813
 */
public class ManageAccounts extends javax.swing.JPanel implements TablePopulatable<Account>,HasTitle{
    private Account account;
    private ParentUI parentUI;
    /**
     * Creates new form ManageAccounts
     */
    public ManageAccounts(ParentUI parentUI,Account account) {
        initComponents();
        this.account = account;
        this.parentUI = parentUI;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUserAccount = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnEnable = new javax.swing.JButton();
        btnEnable1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        tblUserAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Person", "Email", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblUserAccount);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnEnable.setText("Enable");
        btnEnable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnableActionPerformed(evt);
            }
        });

        btnEnable1.setText("Unable");
        btnEnable1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnable1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Users:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(696, 696, 696)
                .addComponent(btnEnable)
                .addGap(18, 18, 18)
                .addComponent(btnEnable1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnable)
                    .addComponent(btnDelete)
                    .addComponent(btnEnable1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
        Account acc = getSelected();
        if (acc == null) {
            return;
        }
        EcoSystem.getInstance().getAllAccountArrayList().remove(acc);
        JOptionPane.showMessageDialog(this, "You are all set");
        populateTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEnableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnableActionPerformed
        
        Account acc = getSelected();
        if (acc == null) {
            return;
        }
        acc.setActive(true);
        JOptionPane.showMessageDialog(this, "You are all set");
        populateTable();
    }//GEN-LAST:event_btnEnableActionPerformed

    private void btnEnable1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnable1ActionPerformed
        
        Account acc = getSelected();
        if (acc == null) {
            return;
        }
        acc.setActive(false);
        JOptionPane.showMessageDialog(this, "You are all set");
        populateTable();
    }//GEN-LAST:event_btnEnable1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEnable;
    private javax.swing.JButton btnEnable1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUserAccount;
    // End of variables declaration//GEN-END:variables

    @Override
    public JTable getTable() {
        return tblUserAccount;
    }

    @Override
    public Object[] populateRow(Account element) {
        return new Object[]{element,element.getPerson(),element.getPerson().getEmail(),element.isActive()};
    }

    @Override
    public String getTitle() {
        return "ManageUserAccount";
    }

    @Override
    public void populateTable() {
        populateTable(EcoSystem.getInstance().getSystemAccountCatalog().getAccountArrayList());
    }
}
