/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.sysadmin;

import biz.EcoSystem;
import biz.account.Account;
import biz.enterprises.AdCompanyEnterprise;
import biz.enterprises.ECOEnterprise;
import biz.enterprises.Enterprise;
import biz.enterprises.NPOEnterprise;
import biz.nw.Network;
import java.util.ArrayList;
import javax.swing.JTable;
import ui.components.TablePopulatable;

/**
 *
 * @author 79813
 */
public class NetworkDetail extends javax.swing.JPanel implements TablePopulatable<Enterprise>{
    private Network network;
    
    /**
     * Creates new form NetworkDetail
     */
    public NetworkDetail(Network network) {
        initComponents();
        this.network = network;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEnterprise = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        tblEnterprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Company Name "
            }
        ));
        jScrollPane1.setViewportView(tblEnterprise);

        jLabel1.setText("Company and College:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEnterprise;
    // End of variables declaration//GEN-END:variables

    @Override
    public JTable getTable() {
        return tblEnterprise;
    }

    @Override
    public Object[] populateRow(Enterprise ent) {
        return new Object[]{ent};
    }

    @Override
    public void populateTable() {
        ArrayList<Enterprise> enterprises = new ArrayList<>();
        enterprises.add(network.getUniversity());
        for(ECOEnterprise eco : network.getEcoCatalog().getEnterprises()){
            enterprises.add(eco);
        }
        for(AdCompanyEnterprise ad : network.getAdCompanyCatalog().getEnterprises()){
            enterprises.add(ad);
        }
        for(NPOEnterprise npo : network.getNpoCatalog().getEnterprises()){
            enterprises.add(npo);
        }
        populateTable(enterprises);
    }
}
