/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.network.university.supervisorOrganization;

import biz.account.Account;
import biz.role.supervisorRole.UniversityDepartmentSupervisorRole;
import biz.video.Report;
import biz.video.Video;
import ui.components.BiubiuBrowser;
import ui.components.HasTitle;
import ui.components.ParentUI;

import javax.swing.*;

/**
 *
 * @author hezj
 */
public class WatchReportedVideo extends javax.swing.JPanel implements HasTitle {
    private Video video;
    private ParentUI parent;

    /**
     * Creates new form WatchVideo
     */
    public WatchReportedVideo(ParentUI parent, Video video) {
        this.video = video;
        this.parent = parent;
        initComponents();
        
        jpWatch.add(BiubiuBrowser.getInstance().view);
        BiubiuBrowser.getInstance().browser.loadURL(video.getUrl());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBan = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jpWatch = new javax.swing.JPanel();

        btnBan.setText("Ban");
        btnBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanActionPerformed(evt);
            }
        });

        btnClear.setText("Clear Report");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jpWatch.setBackground(new java.awt.Color(255, 255, 255));
        jpWatch.setLayout(new javax.swing.BoxLayout(jpWatch, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpWatch, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBan, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClear)
                .addGap(0, 586, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpWatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearReport(video);
        JOptionPane.showMessageDialog(this, "Success!");
        this.parent.popComponent();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanActionPerformed
        video.setStatus(Video.VideoStatus.Banned);
        clearReport(video);
        JOptionPane.showMessageDialog(this, "Success!");
        this.parent.popComponent();
    }//GEN-LAST:event_btnBanActionPerformed

    private void clearReport(Video video) {
        video.getReportCatalog().getReportArrayList().forEach(Report::delete);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBan;
    private javax.swing.JButton btnClear;
    private javax.swing.JPanel jpWatch;
    // End of variables declaration//GEN-END:variables
    @Override
    public String getTitle() {
        return "Censor Reported Video";
    }
}
