/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.network.university.college.Lecturer;

import biz.account.Account;
import biz.video.Video;

import javax.swing.*;

import biz.video.VideoTag;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import ui.components.HasTitle;

/**
 *
 * @author hezj
 */
public class AddOrEditVideo extends javax.swing.JPanel implements HasTitle {
    private Video video;
    private Account account;
    

    /**
     * Creates new form AddOrEditVideo
     */
    public AddOrEditVideo(Account account) {
        this(null, account);
    }
    
    public AddOrEditVideo(Video video, Account account) {
        initComponents();
        
        this.account = account;
        this.video = video;
        btn.setText(video == null ? "Add Video" : "Save Video");
        
        this.cbAdType.removeAllItems();
        this.cbAdType.addItem(Video.VideoAdType.AnyAdd);
        this.cbAdType.addItem(Video.VideoAdType.CommOnly);
        this.cbAdType.addItem(Video.VideoAdType.NoAdd);
        this.cbAdType.addItem(Video.VideoAdType.PSAOnly);
        
        this.cbPrimeOnly.removeAllItems();
        this.cbPrimeOnly.addItem(true);
        this.cbPrimeOnly.addItem(false);

        this.lstTag.removeAll();
        DefaultListModel<VideoTag> listModel = new DefaultListModel<>();
        
        if (video != null) {
            txtTitle.setText(video.getTitle());
            cbAdType.setSelectedItem(video.getTitle());
            txtDescription.setText(video.getDescription());
            txtPicPath.setText(video.getPicPath());
            cbPrimeOnly.setSelectedItem(video.isPrimeOnly());
            txtUrl.setText(video.getUrl());
            
            video.getTagHashSet().forEach(tag -> {
                listModel.addElement(tag);
            });
        }
        lstTag.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        cbAdType = new javax.swing.JComboBox();
        btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtPicPath = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbPrimeOnly = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstTag = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        txtTag = new javax.swing.JTextField();
        btnAddTag = new javax.swing.JButton();
        btnRemoveTag = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();

        jLabel1.setText("Title");

        jLabel2.setText("Description");

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        jLabel3.setText("Ad Type");

        cbAdType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn.setText("btn");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        jLabel4.setText("Pic Path");

        jLabel5.setText("Prime Only");

        cbPrimeOnly.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lstTag.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstTag);

        jLabel6.setText("Tag");

        btnAddTag.setText("↓ Add Tag");
        btnAddTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTagActionPerformed(evt);
            }
        });

        btnRemoveTag.setText("Remove Selected Tag");
        btnRemoveTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveTagActionPerformed(evt);
            }
        });

        jLabel7.setText("URL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(cbPrimeOnly, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAdType, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnAddTag)
                        .addComponent(txtTag)
                        .addComponent(btnRemoveTag)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4)
                        .addComponent(txtPicPath, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addComponent(txtUrl, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(btn))
                .addGap(185, 304, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(136, 136, 136))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbPrimeOnly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbAdType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddTag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPicPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoveTag)
                    .addComponent(btn))
                .addContainerGap(183, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        String title = txtTitle.getText();
        String description = txtDescription.getText();
        String picPath = txtPicPath.getText();
        String url = txtUrl.getText();
        Video.VideoAdType type = (Video.VideoAdType) cbAdType.getSelectedItem();
        boolean isPrimeOnly = (boolean) cbPrimeOnly.getSelectedItem();

        if (title.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Invalid, Title cannot be empty!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
                
        if (picPath.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Invalid, Pic Path cannot be empty!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            new URL(picPath);
        } catch (MalformedURLException e) {
            JOptionPane.showMessageDialog(this, "Invalid, Pic Path is not a valid URL!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
                
        if (url.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Invalid, URL cannot be empty!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            new URL(url);
        } catch (MalformedURLException e) {
            JOptionPane.showMessageDialog(this, "Invalid, URL is not a valid URL!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Video v;
        if (video == null) {
            v = account.getOrg().getEnterprise().getNetwork().getVideoCatalog().newVideo(account);
        } else {
            v = video;
        }
        v.setTitle(title);
        v.setDescription(description);
        v.setPicPath(picPath);
        v.setAdType(type);
        v.setPrimeOnly(isPrimeOnly);
        v.setUrl(url);
        
        v.removeAllTag();
        for (int i = 0; i < lstTag.getModel().getSize(); i++) {
            VideoTag tag = (VideoTag) lstTag.getModel().getElementAt(i);
            v.addTag(tag);
        }

        if (video == null) {
            txtTitle.setText("");
            txtDescription.setText("");
            txtPicPath.setText("");
            txtUrl.setText("");
            txtTag.setText("");
            lstTag.setModel(new DefaultListModel());
            JOptionPane.showMessageDialog(this, "Added");
        } else {
            JOptionPane.showMessageDialog(this, "Saved");
        }
        
    }//GEN-LAST:event_btnActionPerformed

    private void btnRemoveTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveTagActionPerformed
        List selectedTags = lstTag.getSelectedValuesList();
        if (selectedTags.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Select Tag(s) to remove");
            return;
        }
        for (Object tag: selectedTags) {
            ((DefaultListModel) lstTag.getModel()).removeElement(tag);
        }
    }//GEN-LAST:event_btnRemoveTagActionPerformed

    private void btnAddTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTagActionPerformed
        String tagName = txtTag.getText();
        VideoTag tag = account.getOrg().getEnterprise().getNetwork().getVideoTagCatalog().getOrNewTag(tagName);
        for (int i = 0; i < lstTag.getModel().getSize(); i++) {
            if (lstTag.getModel().getElementAt(i).equals(tag)) {
                return;
            }
        }
        ((DefaultListModel) lstTag.getModel()).addElement(tag);
    }//GEN-LAST:event_btnAddTagActionPerformed

    @Override
    public String getTitle() {
        return video == null ? "Add Video" : "Edit Video";
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JButton btnAddTag;
    private javax.swing.JButton btnRemoveTag;
    private javax.swing.JComboBox cbAdType;
    private javax.swing.JComboBox cbPrimeOnly;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lstTag;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtPicPath;
    private javax.swing.JTextField txtTag;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtUrl;
    // End of variables declaration//GEN-END:variables
}
