/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.my;

import biz.account.Account;
import biz.org.unv.UniverseCollegeOrganization;
import ui.components.ChildComponent;
import ui.components.HasTitle;
import ui.components.ParentUI;
import ui.components.TopBar;

import javax.swing.*;
import java.util.Calendar;

/**
 *
 * @author hezj
 */
public class RedeemJPanel extends javax.swing.JPanel implements HasTitle, ChildComponent {
    private Account account;
    private ParentUI parent;
    
    /**
     * Creates new form RedeemJPanel
     */
    public RedeemJPanel(ParentUI parent, Account account) {
        this.account = account;
        this.parent = parent;
        initComponents();
        populateLabel();
        cb.removeAllItems();
        cb.addItem(1);
        cb.addItem(2);
        cb.addItem(3);
        cb.addItem(6);
        cb.addItem(12);
        int cost = ((UniverseCollegeOrganization) account.getOrg()).getPrimeCostPerWeek();
        lblSubtitle.setText(String.format("It will cost you %d coins for one week's Prime membership.", cost));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl = new javax.swing.JLabel();
        cb = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn = new javax.swing.JButton();
        lblSubtitle = new javax.swing.JLabel();

        lbl.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl.setText("jLabel1");

        cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Redeem");

        jLabel2.setText("Week(s)");

        btn.setText("Redeem");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        lblSubtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubtitle.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE))
                    .addComponent(lblSubtitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(392, 392, 392)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn)
                .addContainerGap(529, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        int weeks = (int) cb.getSelectedItem();
        int cost = ((UniverseCollegeOrganization) account.getOrg()).getPrimeCostPerWeek();
        if (weeks * cost > account.getWallet().getCoin()) {
            int res = JOptionPane.showConfirmDialog(
                    this,
                    "Insufficient Coin, do you want to reload? ",
                    "Warning",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE

            );
            if (res == JOptionPane.YES_OPTION) {
                parent.pushComponent(new ReloadCoinJPanel(account));
            }
            return;
        }

        account.getPrimeMembership().redeem(weeks);
        TopBar.getInstance(parent).loggedIn(account);
        populateLabel();
        JOptionPane.showMessageDialog(this, "Success!");
    }//GEN-LAST:event_btnActionPerformed

    private void populateLabel() {
        Calendar expiration = account.getPrimeMembership().getExpiration();
        if (expiration == null) {
            lbl.setText("You are not a Prime Member yet.");
            return;
        }

        long diffInMillies = expiration.getTimeInMillis() - Calendar.getInstance().getTimeInMillis();
        long days = diffInMillies / 1000 / 60 / 60 / 24;
        long weeks = days / 7;
        long rDays = days % 7;
        lbl.setText(String.format("Your Prime Membership will ends in %d week(s) and %d day(s)", weeks, rDays));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JComboBox cb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblSubtitle;
    // End of variables declaration//GEN-END:variables

    @Override
    public void exposed() {
        populateLabel();
    }

    @Override
    public String getTitle() {
        return "Redeem Your Prime Membership";
    }
}
