/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.my;

import biz.account.Account;
import biz.enterprises.UniversityEnterprise;
import ui.components.HasTitle;

import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author hezj
 */
public class ReloadCoinJPanel extends javax.swing.JPanel implements HasTitle {
    private Account account;
    
    /**
     * Creates new form ReloadCoinJPanel
     */
    public ReloadCoinJPanel(Account account) {
        this.account = account;
        initComponents();
        txtTotalPrice.setEnabled(false);
        txtTotalPrice.setText("N/A");
        txtAmount.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateTxtTotalPrice();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateTxtTotalPrice();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateTxtTotalPrice();
            }
        });
    }

    private void updateTxtTotalPrice() {
        Integer amount;
        try {
            amount = parseAmount();
        } catch (Exception e){
            txtTotalPrice.setText("N/A");
            return;
        }
        double totalPrice = account.getOrg().getEnterprise().getNetwork().getCoinPrice(amount);
        txtTotalPrice.setText(String.format("%.2f", totalPrice));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        txtPayment = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtTotalPrice = new javax.swing.JTextField();

        jLabel1.setText("Coin Amount:");

        jLabel2.setText("Payment Info:");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel3.setText("Total Price($):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(355, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSubmit)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAmount)
                            .addComponent(txtPayment)
                            .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(346, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSubmit)
                .addContainerGap(453, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private Integer parseAmount() throws Exception {
        Integer amount;
        try {
            amount = Integer.parseInt(txtAmount.getText());
            if (amount <= 0) {
                throw new Exception("Invalid, amount must be greater than 0.");
            }
            if (amount > 2000) {
                throw new Exception("Invalid, amount must be no greater than 2000");
            }
        } catch (NumberFormatException e) {
            throw new Exception("Invalid, amount must be an integer");
        }
        return amount;
    }

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        Integer amount;
        try {
            amount = parseAmount();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String payment = txtPayment.getText();
        if (payment.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Input Payment Info!", "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        UniversityEnterprise university = (UniversityEnterprise) account.getOrg().getEnterprise();
        university.getReloadCoinOrderCatalog().newReloadCoinOrder(account, amount, payment);

        txtAmount.setText("");
        txtPayment.setText("");
        JOptionPane.showMessageDialog(this, "Submitted, Please wait.");
    }//GEN-LAST:event_btnSubmitActionPerformed

    @Override
    public String getTitle() {
        return "Submit Coin Reload Request";
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtPayment;
    private javax.swing.JTextField txtTotalPrice;
    // End of variables declaration//GEN-END:variables
}
